<?php
return [
  'Kathmandu' => [
    'Anamnagar Area',
    'Bagbazar Area',
    'Asan Area',
    'Basantapur Area',
    'Baluwatar Area',
    'Bhotahiti Area',
    'BishalNagar Area',
    'Boudha Area',
    'Budhanilkanth Area',
    'Chabahil Area',
    'Chandragiri Area',
    'Chhetrapati Area',
    'Gaushala Area',
    'Gokarneshwor Area',
    'Gongabu Area',
    'Hanumandhoka Area',
    'Indrachwok Area',
    'Kalanki Area',
    'Kalimati Area',
    'Kamaladi Area',
    'Kritipur Area',
    'Koteshwor Area',
    'Kuleshwor Area',
    'Lagantole Area',
    'Lainchaur Area',
    'Lazimpat Area',
    'Maharajgunj Area',
    'Maitidevi Area',
    'Maitighar Area',
    'Marutole Area',
    'Min Bhawan Area',
    'Nagarjun Area',
    'Naxal Area',
    'Nayabazar Area',
    'New Baneshwor Area',
    'Putalisadak Area',
    'Raktakali Area',
    'Sinamangal Area',
    'Swayambhu Area',
    'Tarkeshwar Area',
    'Tangal Area',
    'Teku Area',
    'Tinkune Area',
    'Tokha Area',

  ],
  'Bhaktapur' => [
    'Suryabinayak Area',
    'Madhyapur Thimi Area',
    'Changunarayan Area'
  ],
  'Lalitpur' => [
    'Kupondole Area',
    'Jhamsikhel Area',
    'Sanepa Area',
    'Pulchwok Area',
    'Jawalakhel Area',
    'Kumaripati Area',
    'Patan Hospital Area',
    'Kanibahal Area',
    'Balkumari Area',
    'Banglamukhi Area',
    'Thina Area',
    'Kusunti Area',
    'Lagankhel Area',
    'Satdobato Area',
    'MangalBazar Area',
    'Gwarko Area',
    'Machhindrabahal Area',
    'Nakhipot Area',
    'Bhaisepati Area',
    'Bungamati Area',
    'Chokhel Area',
    'Dhapakhel Area',
    'Harisiddhi Patan Area',
    'Imadole Area',
    'Khokana Karyabinayak Area',
    'Nakhu Area',
    'Sunakoti Area',
    'Tikathali Area',
  ],
  'Others' => []
];